### ISSUE TITLE
list of interested parties (and progress)

### ISSUE THREAD

**Issue by dwinston** [materialsproject/MPContribsUsers#5]
I know there are open issues that are tracking the development of significant, in-progress user contribution flows.

However, @computron mentioned that it would be nice to maintain a list of interested parties (beyond the current two for which you are active). This would be useful also for preparing a report for the upcoming  DOE management review. Perhaps we could maintain a md file in this repo for this?

**Comment by tschaume** [comment]
The list can be found [here](https://github.com/tschaume/mp-docs/blob/master/data_contributors.asc) and is kept up-to-date from now on. It's currently in a protected repo and I'm not sure we can make it publicly available. If so, I'll probably make it part of the wiki. @kristinpersson ?

**Comment by kristinpersson** [comment]
Do we want to make it public - and if so why?

K

On Thu, Jul 9, 2015 at 12:57 PM, Patrick Huck <notifications@github.com>
wrote:

> The list can be found here
> <https://github.com/tschaume/mp-docs/blob/master/data_contributors.asc>
> and is kept up-to-date from now on. It's currently in a protected repo and
> I'm not sure we can make it publicly available. If so, I'll probably make
> it part of the wiki. @kristinpersson <https://github.com/kristinpersson> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/materialsproject/MPContribsUsers/issues/5#issuecomment-120127623>
> .
>



-- 
-- 
Dr Kristin A Persson
Lawrence Berkeley National Laboratory
1 Cyclotron Road, MS 70R0108B
Berkeley, CA 94720
Phone: (510) 486-7218
Web: http://eetd.lbl.gov/staff/kristin-persson

**Comment by dwinston** [comment]
No need for it to be public. I didn't realize it already existed in another repo. Looks good to me.
