### ISSUE TITLE
Order of process parametes not preserved

### ISSUE THREAD

**Issue by ATNDiaye** [materialsproject/MPContribsUsers#8]
The order of the process parameters is not preserved in the scan_params.

"process_template": {
    "Fe_XMCD": {
      "get_xmcd": {
        "energy_range": "690 740"
      },
      "scaling_preedge_to_1": {
        "preedge_range": "765 772"
      }
    }
 }

gives:

RecursiveDict([
(u'scaling_preedge_to_1', RecursiveDict([(u'preedge_range', u'765 772')])), 
(u'get_xmcd', RecursiveDict([(u'energy_range', u'690 740')]))
])

If I only put the get_xmcd line in, then the scan_params seem to be empty.

**Comment by tschaume** [comment]
superseded by #34
